all:
	gcc -c uthread.c
	gcc -c queue.c
	ar rcs mythread.a uthread.o queue.o
	gcc -c uthread_example1.c
	gcc -c uthread_example2.c
	gcc -c uthread_example3.c
	gcc -c uthread_example4.c
	gcc -c uthread_example5.c